set shell := ["zsh", "-cu"]

default:
  @just --list

build:
  swift build -c release --product NeatCLI

install:
  ./scripts/install-neat.sh

install-local:
  ./scripts/install-neat.sh --local

uninstall:
  ./scripts/install-neat.sh --uninstall

reinstall *args:
  bash ./scripts/reinstall-neat.sh {{args}}

preview:
  bash ./scripts/reinstall-neat.sh ../NeatExample --yes
  neat run ../NeatExample
