id = "neat"
name = "Neat"
version = "0.2.11"
schema_version = 1
authors = ["Neat Team"]
description = "Neat language support for .neat files."
repository = "https://github.com/georgeneat/Neat"
languages = ["languages/neat"]

[lib]
kind = "Rust"
version = "0.7.0"

[grammars.neat]
repository = "file:///Users/george/Documents/WebProjects/Neat"
rev = "8e9ccd37c98d3b0538ecdb18160df11e779f4041"
path = "zed/neat/grammars/tree-sitter-neat"

[language_servers.neat-lsp]
name = "Neat LSP"
language = "Neat"
languages = []

[language_servers.neat-lsp.language_ids]
Neat = "neat"
