id = "neat"
name = "Neat"
version = "0.1.0"
schema_version = 1
authors = ["Neat Team"]
description = "Neat language support for .neat files."
repository = "https://github.com/georgeneat/Neat"
languages = ["languages/neat"]

[grammars.neat]
repository = "file:///Users/george/Documents/WebProjects/Neat/zed/neat/grammars/tree-sitter-neat"
rev = "main"

[lib]
kind = "Rust"
version = "0.7.0"

[language_servers.neat-lsp]
name = "Neat LSP"
languages = ["Neat"]

[language_servers.neat-lsp.language_ids]
Neat = "neat"
