id = "neat"
name = "Neat"
version = "0.2.34"
schema_version = 1
authors = ["Neat Team"]
description = "Neat language support for .neat files."
repository = "https://github.com/georgeneat/Neat"
languages = ["languages/neat"]

[lib]
kind = "Rust"
version = "0.7.0"

[grammars.neat]
repository = "file:///Users/george/Documents/Neat"
rev = "038e140d8ca03db2cb94ccd10f3c33b44af908d5"
path = "zed/neat/grammars/tree-sitter-neat"

[language_servers.neat-lsp]
name = "Neat LSP"
language = "Neat"
languages = ["Neat"]

[language_servers.neat-lsp.language_ids]
Neat = "neat"
