set shell := ["zsh", "-cu"]

default:
  @just --list

build:
  swift build -c release --product GradientCLI

install:
  ./scripts/install-gradient.sh

install-local:
  ./scripts/install-gradient.sh --local

uninstall:
  ./scripts/install-gradient.sh --uninstall

reinstall *args:
  bash ./scripts/reinstall-gradient.sh {{args}}

preview:
  bash ./scripts/reinstall-gradient.sh ../GradientExample --yes
  gradient run ../GradientExample
