#!/usr/bin/env ruby
# frozen_string_literal: true

require "optparse"

ROOT = File.expand_path("..", __dir__)
GENERATED_PATH = File.join(
  ROOT,
  "RangeSyntax/Sources/RangeSyntax/Lexer/Lexer+Generated.swift"
)

SOURCE_RELATIVE_PATHS = [
  "RangeCompiler/Lexer/ASCII.range",
  "RangeCompiler/Lexer/Lexer.range",
  "RangeCompiler/Lexer/LexerRule.range",
  "RangeCompiler/Lexer/LexicalToken.range",
  "RangeCompiler/Lexer/RangeLexer.range",
  "RangeCompiler/Lexer/SourceLocation.range",
  "RangeCompiler/Lexer/SourceRange.range",
  "RangeCompiler/Lexer/TokenKind.range"
].freeze

options = {
  check: false,
  print: false
}

OptionParser.new do |parser|
  parser.on("--check") { options[:check] = true }
  parser.on("--print") { options[:print] = true }
end.parse!

def source_path(relative_path)
  File.join(ROOT, relative_path)
end

def fingerprint
  hash = 14_695_981_039_346_656_037
  feed = lambda do |byte|
    hash ^= byte
    hash = (hash * 1_099_511_628_211) & 0xffff_ffff_ffff_ffff
  end

  SOURCE_RELATIVE_PATHS.each do |relative_path|
    relative_path.bytes.each { |byte| feed.call(byte) }
    feed.call(0)
    File.binread(source_path(relative_path)).bytes.each { |byte| feed.call(byte) }
    feed.call(255)
  end

  "%016x" % hash
end

def token_cases
  File.read(source_path("RangeCompiler/Lexer/TokenKind.range")).lines.map do |line|
    stripped = line.strip
    next unless stripped.start_with?("case ")

    match = stripped.match(/\Acase\s+([A-Za-z_][A-Za-z0-9_]*)(?:\((.*)\))?\z/)
    abort("Could not parse token case: #{stripped}") unless match

    name = match[1]
    associated = match[2]
    labels = associated ? associated.split(",").map { |part| part.split(":").first.strip } : []
    {
      name: name,
      declaration: associated ? "case #{name}(#{associated})" : "case #{name}",
      labels: labels
    }
  end.compact
end

def lexer_rules
  File.read(source_path("RangeCompiler/Lexer/RangeLexer.range")).scan(
    /LexerRule\(name: "((?:\\.|[^"])*)", pattern: "((?:\\.|[^"])*)", token: "((?:\\.|[^"])*)", priority: ([0-9]+)\)/
  ).map do |name, pattern, token, priority|
    {
      name: name,
      pattern: pattern,
      token: token,
      priority: priority.to_i
    }
  end
end

def switch_pattern(token_case)
  name = token_case[:name]
  labels = token_case[:labels]
  return ".#{name}" if labels.empty?

  captures = labels.map { |label| "let #{label}" }.join(", ")
  ".#{name}(#{captures})"
end

def parser_token_expression(token_case)
  name = token_case[:name]
  labels = token_case[:labels]

  case name
  when "integer"
    [
      "guard let integer = Int(value) else {",
      "    throw ParseError(\"Invalid integer literal \\(value).\", range: token.range)",
      "}",
      "parserToken = .integer(integer)"
    ]
  when "double"
    [
      "guard let double = Double(value) else {",
      "    throw ParseError(\"Invalid numeric literal \\(value).\", range: token.range)",
      "}",
      "parserToken = .double(double)"
    ]
  when "foreignBody"
    "parserToken = .foreignBody(language: language, text: text)"
  when "macroAttribute"
    "parserToken = .macroAttribute(name: name, argument: argument)"
  when "identifier", "markerAttribute", "stringLiteral", "keyword"
    "parserToken = .#{name}(value)"
  else
    if labels.empty?
      "parserToken = .#{name}"
    else
      abort("No parser-token conversion rule for #{name}")
    end
  end
end

def generated_source
  cases = token_cases
  rules = lexer_rules

  token_kind = cases.map { |token_case| "    #{token_case[:declaration]}" }.join("\n")

  conversion_cases = cases.map do |token_case|
    expressions = Array(parser_token_expression(token_case))
    body = expressions.map { |expression| "            #{expression}" }.join("\n")
    "        case #{switch_pattern(token_case)}:\n#{body}"
  end.join("\n")

  rule_lines = rules.map do |rule|
    "        RangeAuthoredLexerRule(name: \"#{rule[:name]}\", pattern: \"#{rule[:pattern]}\", token: \"#{rule[:token]}\", priority: #{rule[:priority]})"
  end.join(",\n")

  <<~SWIFT
    import Foundation

    // Generated by scripts/generate-range-lexer-bootstrap.rb.
    // Range lexer source fingerprint: #{fingerprint}
    // Source of truth: RangeCompiler/Lexer/*.range.

    enum RangeAuthoredTokenKind {
    #{token_kind}
    }

    extension Lexer {
        static func convertGenerated(_ token: RangeAuthoredLexicalToken) throws -> LexedToken {
            let parserToken: Token
            switch token.kind {
    #{conversion_cases}
            }
            return LexedToken(token: parserToken, range: token.range)
        }
    }

    extension RangeAuthoredLexer {
        static let generatedRules: [RangeAuthoredLexerRule] = [
    #{rule_lines}
        ]
    }
  SWIFT
end

generated = generated_source

if options[:print]
  print generated
elsif options[:check]
  current = File.exist?(GENERATED_PATH) ? File.read(GENERATED_PATH) : nil
  if current == generated
    puts "Range lexer bootstrap is current."
  else
    warn "Range lexer bootstrap is stale. Run: ruby scripts/generate-range-lexer-bootstrap.rb"
    exit 1
  end
else
  File.write(GENERATED_PATH, generated)
  puts "Wrote #{GENERATED_PATH}"
end
