**

!Website/
!Website/**
!RangeCompiler/
!RangeCompiler/Sources/
!RangeCompiler/Sources/Core/
!RangeCompiler/Sources/Core/Macro/
!RangeCompiler/Sources/Core/Macro/Codable.range
!Benchmarks/
!Benchmarks/Speed/
!Benchmarks/Speed/results/
!Benchmarks/Speed/results/latest.json

Website/.DS_Store
Website/.env
Website/.env.*
Website/.git
Website/.svelte-kit
Website/build
Website/coverage
Website/node_modules
Website/*.db
Website/*.db-shm
Website/*.db-wal
